name: openEO_downScaleML
channels:
  - conda-forge
dependencies:
  - python=3.11.11
  - pip

  # Zarr and Dask stack
  - zarr==2.13.3
  - xarray==2024.3.0
  - numpy==1.26.4
  - scikit-learn==1.6.1
  - pandas==2.2.3
  - tqdm==4.67.1
  - joblib==1.4.2
  - lightgbm==4.6.0
  - distributed==2025.1.0
  - dask==2025.1.0

  - pip:
      - git+https://github.com/interTwin-eu/openeo-processes-dask.git@feature/merge_cubes_issue#egg=openeo-processes-dask[implementations]
      - git+https://gitlab.inf.unibz.it/earth_observation_public/raster-to-stac.git@update_url#egg=raster-to-stac
